### ISSUE TITLE
https://a.pomf.cat is a phishing site?

### ISSUE THREAD

**Issue by gabri25ele** [Inirit/Reuploader#2]
Nod32 says "https://a.pomf.cat/" is a phishing site.
like this
https://s18.postimg.org/clrxm2hpl/Cattura.png

**Comment by Inirit** [comment]
As far as I can tell, the only reason pomf.cat could be flagged as a malicious site is because some users have abused the service by either A) uploading password dump text files for distribution, or B) uploading malware for distribution. A isn't really a risk to anyone, just an unfortunate situation, and B is entirely avoided when the only links being used are ones you've created yourself.

I haven't found any other evidence to suggest that the service itself is malicious, if that changes then I will remove support for it from the extension. However, it's up to you whether or not you want to use this particular service, only the service you've selected in the extension's options menu will be used when uploading an image.

**Comment by Inirit** [comment]
Also, a quick disclaimer, I am not directly associated with pomf.cat nor do I have any legitimate insight to the inner workings of the service. The information I described above is the result of some research via Google combined with my own opinion.
