### ISSUE TITLE
Add new service - ImageShack

### ISSUE THREAD

**Issue by AntMadeira** [Inirit/Reuploader#4]
I there.
Would it be possible to add imageshack support?

Regards.

**Comment by Inirit** [comment]
Most likely. I will look into it this week.

**Comment by AntMadeira** [comment]
Thank you very much for considering it!

**Comment by Inirit** [comment]
I was going to start on this tonight, but I may not actually be able to support ImageShack after all. If I recall correctly, ImageShack used to be a straightforward image upload service which is why I figured it would be easy, but I guess they entirely changed their site sometime in the last decade and now you need to have a premium account to upload images. While I could use the 30 day trial to implement support for it, I wouldn't be able to go back and fix anything if bugs are discovered or their service changes because I'd no longer be able to test my own code.

That being said, it looks like ImageShack has their own kind of "image scraping" tool by the name of "Shack It". It's not quite the same way of doing things, but it appears to achieve the same goal. I've never used it and I have no idea how well it works, but you can take a look at it here if you're interested: 

https://imageshack.com/shackit

**Comment by AntMadeira** [comment]
I understand.
Just for reference, before this major Firefox update, I used Rehost Image, which worked fine with imageshack.
Maybe you can take some ideas from it.

About shackit, I can't login in my account with it when I'm in a webpage, so it's kind of useless. :/
